quarkus:
  log:
    level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p [%c] (%t) %s%e%n"
    category:
      "org.reflections":
        level: ERROR
      "io.github.lburgazzoli.quarkus.ck.ConnectConfig":
        level: ERROR
      "org.apache.kafka.clients.admin.AdminClientConfig":
        level: ERROR
      "org.apache.kafka.connect.runtime.SourceConnectorConfig":
        level: ERROR
      "org.apache.kafka.connect.runtime.ConnectorConfig":
        level: ERROR
      "org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig":
        level: ERROR
      "org.apache.kafka.connect.json.JsonConverterConfig":
        level: ERROR
      "org.apache.kafka.connect.runtime.WorkerConfig":
        level: ERROR
      "org.apache.kafka.clients.producer.ProducerConfig":
        level: ERROR
      "org.apache.kafka.clients.consumer.ConsumerConfig":
        level: ERROR
      "org.apache.kafka.connect.runtime.TaskConfig":
        level: ERROR


kc:
  id: "${worker.id}"
  prometheus:
    config: "etc/kafka_connect_metrics.yaml"
  worker:
    # rpk container start --nodes 3
    bootstrap.servers: '127.0.0.1:56697,127.0.0.1:56694,127.0.0.1:56687'
    #security.protocol: "SASL_SSL"
    #sasl.mechanism: "PLAIN"
    #sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${kafka.username}" password="${kafka.password}";'
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    #offset.storage.file.filename: "/tmp/${worker.id}-offset.txt"
    offset.flush.interval.ms: 10000
    offset.storage.topic: "${worker.id}-offset"
    topic.creation.default.replication.factor: -1
    topic.creation.default.partitions: -1
    topic.creation.default.cleanup.policy: "compact"
    topic.creation.default.delete.retention.ms: 2678400000
  connectors:
    # docker run -d -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres debezium/example-postgres:1.4
    debezium:
      type: "io.debezium.connector.postgresql.PostgresConnector"
      config:
        tasks: 1
        tasks.max: 1
        topic.prefix: "${worker.id}_"
        database.hostname: "localhost"
        database.user: "postgres"
        database.password: "postgres"
        database.dbname: "postgres"
        topic.creation.default.replication.factor: -1
        topic.creation.default.partitions: -1
        topic.creation.default.cleanup.policy: "compact"
        topic.creation.default.delete.retention.ms: 2678400000
