kc:
  id: "${quarkus.uuid}"
  worker:
    bootstrap.servers: localhost:9092
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    offset.flush.interval.ms: 10000
    offset.storage.topic: "foo"

